# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

# /tell や /msg や /r コマンドでプライベートメッセージを送信するときに、
# 適用されるフォーマット設定。
defaultFormatForPrivateMessage: '&7[%sender@%senderserver > %reciever@%recieverserver] %msg'

# ローマ字をかな文字や漢字に変換する設定。
# none/kana/GoogleIME/SocialIME の4つのいずれかが設定可能。
# none      : 変換なし。
# kana      : かな変換のみ。
# GoogleIME : かな変換したのち、GoogleIMEを使って漢字変換する。
# SocialIME : かな変換したのち、SocialIMEを使って漢字変換する。
japanizeType: GoogleIME

# Japanize変換されたメッセージ部分の、表示フォーマット設定。
japanizeLine1Format: '%msg &7(%japanize)'
